{
 "title": "maker-faire",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "<font size=\"1200\">Insigno: pulisci divertendoti!</font>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "verifiche totali",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM image_verifications LIMIT 50 "
    },
    {}
   ]
  },
  {
   "title": "Immagini totali",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"immagini totali\" FROM marker_images LIMIT 50 "
    },
    {
     "rawSql": "SELECT\n  COUNT(id) AS \"immagini verificate\"\nFROM\n  marker_images\nWHERE verify_number>=3"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"admin ok\" FROM  marker_images WHERE approved=TRUE  LIMIT 50 "
    }
   ]
  },
  {
   "title": "Caricate oggi",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rocket_http_requests_total{endpoint=\"/map/image/add\", status=\"200\"}[14h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "marker",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT ST_X(ST_GeomFromEWKT(point)) as longitude, ST_Y(ST_GeomFromEWKT(point)) as latitude FROM markers"
    }
   ]
  },
  {
   "title": "Immagini caricate",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT id FROM (SELECT id FROM marker_images WHERE approved IS TRUE ORDER BY id DESC\nLIMIT 20)lol ORDER BY RANDOM() LIMIT 1"
    }
   ]
  },
  {
   "title": "Classifica del giorno",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT name, points FROM special_scoreboard();"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Utenti FROM users WHERE id > 316"
    }
   ]
  }
 ]
}