[default]
oldest_supported_version="0.0.2"

# our custom config data
media_folder = "./media"
template_folder = "./templates"
intro_images = []

[default.smtp]
    user = ""
    password = ""
    server = ""
    from_mail ="Insigno <insigno@test.test>"
    port = 587

[default.scrypt]
    log_n = 11
    r = 8
    p = 1
    len = 30

[default.databases.db]
    url = "postgres://mindshub:test@postgres:5432/insignorocketdb"
    timeout = 5
    pool_size = 5