# ./Rocket.toml

[default.databases]
db = {url = "postgres://mindshub:Minds.100@insignio.mindshub.it:5432/insigniorocketdb", timeout = 10, pool_size = 5}

[debug]
log_level = "debug"

[release]


[default]
media_folder= "/home/alessio/Documents/Mindshub/insignio/insignio_backend/testi"
secret_key = "/ArczfDUOXuoxJwvf1BhfkPGCoaeXK5x0eblZQiCzXs="