# Generated by Django 4.0.5 on 2022-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Undifferentiated', 'Undifferentiated'), ('Glass', 'Glass'), ('Compost', 'Compost'), ('Electronics', 'Electronics')], default='Undifferentiated', max_length=20),
        ),
    ]
