# Generated by Django 4.0.5 on 2022-10-24 11:38

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_marker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='x',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='y',
        ),
        migrations.AddField(
            model_name='marker',
            name='xy',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(45.0, 10.0), srid=4326),
        ),
    ]
