# Generated by Django 4.0.5 on 2022-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_marker_x_remove_marker_y_marker_xy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('undifferentiated', 'Undifferentiated'), ('glass', 'Glass'), ('compost', 'Compost'), ('electronics', 'Electronics')], default='undifferentiated', max_length=20),
        ),
    ]
