# Generated by Django 4.0.3 on 2022-10-26 18:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_marker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='xy',
            field=django.contrib.gis.db.models.fields.GeometryField(default=django.contrib.gis.geos.point.Point(45.0, 10.0, srid=4326), srid=4326),
        ),
    ]
