# Generated by Django 4.0.5 on 2022-10-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_marker_xy'),
        ('map', '0006_marker_creationdate_alter_marker_xy_markerimage'),
    ]

    operations = [
    ]
