# Generated by Django 4.0.5 on 2022-10-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_merge_20221026_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markerimage',
            name='marker_id',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='MarkerImage',
        ),
    ]
