# Generated by Django 4.0.5 on 2022-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0010_remove_markerimage_marker_id_delete_marker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
