# Generated by Django 4.0.5 on 2022-10-26 20:14

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', django.contrib.gis.db.models.fields.GeometryField(default=django.contrib.gis.geos.point.Point(45.0, 10.0, srid=4326), srid=4326)),
                ('type', models.CharField(choices=[('unknown', 'Unknown'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('undifferentiated', 'Undifferentiated'), ('glass', 'Glass'), ('compost', 'Compost'), ('electronics', 'Electronics')], default='undifferentiated', max_length=20)),
                ('creationDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='MarkerImage',
        ),
    ]
