# Generated by Django 4.0.5 on 2022-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_marker_delete_markerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('marker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
    ]
