# Generated by Django 4.0.5 on 2022-10-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_markerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='type',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='xy',
        ),
        migrations.DeleteModel(
            name='MarkerImage',
        ),
    ]
