# Generated by Django 4.0.5 on 2022-10-26 20:23

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_marker_creationdate_remove_marker_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='creationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('undifferentiated', 'Undifferentiated'), ('glass', 'Glass'), ('compost', 'Compost'), ('electronics', 'Electronics')], default='undifferentiated', max_length=20),
        ),
        migrations.AddField(
            model_name='marker',
            name='xy',
            field=django.contrib.gis.db.models.fields.GeometryField(default=django.contrib.gis.geos.point.Point(45.0, 10.0, srid=4326), srid=4326),
        ),
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('marker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
    ]
