# Generated by Django 4.0.5 on 2022-10-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_marker_creationdate_marker_type_marker_xy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markerimage',
            name='marker_id',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='MarkerImage',
        ),
    ]
