# Generated by Django 4.0.5 on 2022-10-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markerimage',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
