# Generated by Django 4.0.5 on 2022-10-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_alter_markerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markerimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
