# Generated by Django 4.0.3 on 2022-03-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PillQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('is_multiple_choice', models.BooleanField()),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pills.pill')),
            ],
        ),
        migrations.CreateModel(
            name='PillAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('pill_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pills.pillquestion')),
            ],
        ),
    ]
