# Generated by Django 4.0.3 on 2022-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pill',
            name='source',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
