# Generated by Django 4.0.3 on 2022-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0002_pill_author_pill_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
