[default]
oldest_supported_version="0.0.2"

# our custom config data
media_folder = "/app/media"
template_folder = "/app/templates"
intro_images = ["0.jpg", "1.jpg", "2.gif", "3.jpg", "4.gif", "5.jpg", "6.jpg"]
secret_key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
             
[default.smtp]
    user = ""
    password = ""
    server = ""
    from_mail ="Insigno <insigno@test.test>"
    port = 587

[default.scrypt]
    log_n = 11
    r = 8
    p = 1
    len = 30

[default.databases.db]
    url = "postgres://root:test@postgresql:5432/root"
    timeout = 5
    pool_size = 5