global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - prometheus:9090

  - job_name: rocket
    metrics_path: /metrics
    static_configs:
    - targets:
      - insigno:8000
  
  - job_name: postgresql_exporter
    metrics_path: /metrics
    static_configs:
    - targets:
      - postgresql_exporter:9187

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
    - targets:
      - node_exporter:9100