name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: target/release/insignio
        asset_name: insignio
        tag: ${{github.ref}}
        overwrite: true
        body: "Release file"
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASS}}
        port: ${{secrets.SSH_PORT}}
        source: "target/release/insignio"
        target: "insignio"
    
